### ISSUE TITLE
Improvement suggestions.

### ISSUE THREAD

**Issue by jiegec** [darksmile/cheatsheet#3]
1. Add a function to add cheats in the same group in one function call.
2. Add some key bindings to move between groups. M-n, M-p can be ok.

Sorry my elisp level is low so i am not sure i can make a good pull request.

**Comment by donderom** [comment]
I use a simple function for adding cheats to the same group. The usage of it looks like this:
```elisp
(cheatsheet-add-group 'GroupName
                                        '(:key "key1" :description "desc1")
                                        '(:key "key2" :description "desc2"))
```
@darksmile Do you think it's worth it to add something like this as public API?

**Comment by darksmile** [comment]
@donderom I'm using the same function a well. Adding as a public API is fine, but I will not be available for the next couple of weeks. If you want to create a PR, I'll merge. If not - will do this a bit later. Thanks!
